version: '3.8'

services:
  redis_db:
    image: redis:alpine
    ports:
      - "6379:6379"

  server:
    container_name: "server"
    build: .
    command: python ./main.py
    restart: "always"
    ports:
      - "8000:8000"

    depends_on:
      - redis_db

    environment:
      - HOST=0.0.0.0
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
